# Generated by Django 3.2.9 on 2021-11-11 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{3}-\\d{3,4}-\\d{4}$')]),
        ),
    ]
