# Generated by Django 3.2.5 on 2021-11-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_auto_20211117_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_star',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='1', max_length=5),
        ),
    ]
