# Generated by Django 3.2.5 on 2021-11-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_alter_review_review_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_star',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=5),
        ),
    ]
